targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true
          any_map: true
          explicit_to_json: true
      # 自動生成ファイルの冒頭に ignore_for_file コメントを付加するための設定。
      # これをすることで analyzer の exclude に lib/**/**.g.dart などを書かなくて良くなる。
      # https://twitter.com/_mono/status/1536907416864169987
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - implicit_dynamic_parameter
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type
            - unnecessary_cast
            - todo
